config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

admin.site.index_title = _('MAURISOUQ')
admin.site.site_header = _('MAURISOUQ Administration')
admin.site.site_title = _('MAURISOUQ Management')

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/",TemplateView.as_view(template_name="pages/about.html"),name="about",),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("user/",include("elmarse.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("core/",include("elmarse.core.urls", namespace="core")), 
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/",default_views.bad_request,kwargs={"exception": Exception("Bad Request!")},),
        path("403/",default_views.permission_denied,kwargs={"exception": Exception("Permission Denied")},),
        path("404/",default_views.page_not_found,kwargs={"exception": Exception("Page not Found")},),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

elmarse/core/urls.py
from django.urls import path

from .views import (
    product_list_view,
    product_create_view,
    product_update_view,
    product_delete_view,
    product_detail_view,
    usershop_detail_view,
    usershop_update_view,
    usershop_list_view,
    usershop_create_view,
    usershop_delete_view,
    approve_view,
    revoke_view
)
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views
from .models import Activity,Product

app_name = "core"



urlpatterns = [
     # #############################################################################
    # #                                 Product                                 # #
    # #############################################################################
    path("product/list", view = product_list_view, name="product-list"),
    path('product/create/', product_create_view, name='product-create'),
    path('product/update/<int:pk>/', product_update_view, name='product-update'),
    path('product/<int:pk>/delete/', product_delete_view, name='product-delete'),
    path('product/detail/<int:pk>/', product_detail_view, name='product-detail'),
    # #############################################################################
    # #                                 UserShop                                # #
    # #############################################################################
    path("shop/list", view = usershop_list_view, name="usershop-list"),
    path('shop/create/', usershop_create_view, name='usershop-create'),
    path('shop/detail/<int:pk>/', usershop_detail_view, name='usershop-detail'),
    path('shop/<int:pk>/delete/', usershop_delete_view, name='usershop-delete'),
    path('shop/update/<int:pk>/', usershop_update_view, name='usershop-update'),
    # #############################################################################
    # #                                 Admin                                 # #
    # #############################################################################
    path('approve/<int:user_pk>/', approve_view, name='user-approve'),
    path('revoke/<int:user_pk>/', revoke_view, name='user-revoke'),
]

elmarse/users/urls.py
from django.urls import path

from elmarse.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_delete_view
)

app_name = "users"
urlpatterns = [
    path("list", view=user_list_view, name="list"),
    path("redirect/", view=user_redirect_view, name="redirect"),
    path("update/<str:pk>/", view=user_update_view, name="update"),
    path("delete/<str:pk>/", view=user_delete_view, name="delete"),
    path("detail/<str:pk>/", view=user_detail_view, name="detail"),
]

elmarse/core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model
from allauth.account.signals import user_signed_up
# Create your models here.
import hashlib
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse, reverse_lazy
from allauth.account.signals import user_signed_up

User = get_user_model()

ELECTRONIQUE = 'electronic'
CLOTHES = 'clothes'
CATEGORIES = (
    (ELECTRONIQUE, 'Electronique - إلكتروني'),
    (CLOTHES, 'Vêtements - ملابس'),
)
from django.db.models import Sum
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey



# #############################################################################
# #                                 Chat Message                            # #
# #############################################################################
class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, _('Dialog')),
        (CHAT, _('Chat'))
    )

    type = models.CharField(
        _('Тип'),
        max_length=1,
        choices=CHAT_TYPE_CHOICES,
        default=DIALOG
    )
    members = models.ManyToManyField(User, verbose_name=_("Member"))

    @models.permalink
    def get_absolute_url(self):
        return 'core:chat-messages', (), {'chat_id': self.pk }


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=_("Chat"),on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=_("User"),on_delete=models.CASCADE)
    message = models.TextField(_("Message"))
    pub_date = models.DateTimeField(_('Message date'), default=timezone.now)
    is_readed = models.BooleanField(_('Readed'), default=False)

    class Meta:
        ordering=['pub_date']

    def __str__(self):
        return self.message



 # #############################################################################
 # #                              LikeDislike                                # #
 # #############################################################################

class ActivityManager(models.Manager):
    use_for_related_fields = True
    @property
    def likes(self):
        # We take the queryset with records greater than 0
        return self.get_queryset().filter(activity_type=1)
    def liked(self,user):
        # We take the queryset with records greater than 0
        return self.get_queryset().filter(user=user,activity_type=1).first()

    def followers(self):
        # We take the queryset with records less than 0
        return self.get_queryset().filter(activity_type=-1)

    def products(self):
        return self.get_queryset().filter(content_type__model='product')

    def shops(self):
        return self.get_queryset().filter(content_type__model='usershop')


class Activity(models.Model):
    LIKE = 1
    FOLLOW = -1

    ACTIVITIES = (
        (FOLLOW, 'Follow'),
        (LIKE, 'Like')
    )

    activity_type = models.SmallIntegerField(verbose_name=_("activity type"), choices=ACTIVITIES)
    user = models.ForeignKey(User, verbose_name=_("user"),on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')


    objects = ActivityManager()
    def __str__(self):
        return str(self.object_id)
# #############################################################################
# #                                 UserShop                                # #
# #############################################################################

class UserShopManager(models.Manager):
    def get_queryset(self):
        return super(UserShopManager, self).get_queryset().filter(user__is_shopowner=True)

class UserShop(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name= _('User'),
                                related_name='shop',on_delete=models.CASCADE)
    name = models.CharField( _('Shop name'),max_length=100, default = _('Shop name'))
    address = models.CharField( _('Address'),max_length=100, default = _('Shop address'))
    city = models.CharField(_('City'),max_length=100, default='')
    phone = models.IntegerField(_('Phone number'),default=3344556677)
    avatar = models.ImageField(_('Avatar'),blank=True,default='../media/storeavatar.jpg')
    image = models.ImageField( _('Image'),blank=True,default='../media/store.jpg')
    description = models.CharField( _('Description'),max_length=200, default = _('Shop description'))
    followers = models.IntegerField(default=0)
    posts = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add = True,blank=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True)
    activities = GenericRelation(Activity, related_query_name='shops')
    objects = UserShopManager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name + self.user.username

    def get_absolute_url(self):
        return reverse('core:usershop-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('core:usershop-update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('core:usershop-delete', kwargs={'pk': self.pk})

def create_shop(sender, **kwargs):
    if kwargs['created']:
        user_shop = UserShop.objects.create(user=kwargs['instance'],name="Store name")


post_save.connect(create_shop, sender=User)

# #############################################################################
# #                                 UserProfile                             # #
# #############################################################################
def sent(num,body,is_client):
    client = Client(settings.ACCOUNT_SID, settings.AUTH_TOKEN)
    if(is_client):
        msg = client.api.account.messages.create(to = num,from_= 'Ghaza Telecom',body= body)
    else:
        msg = client.api.account.messages.create(to = num,from_= settings.TWILIO_NUM,body= body)
    return msg
class UserProfile(models.Model):
    """Profile data about a user.
    """
    user = models.OneToOneField(User, primary_key=True, verbose_name= _('User'), related_name='profile',
                                on_delete=models.CASCADE)
    avatar_url = models.CharField(max_length=256, blank=True, null=True)
    avatar = models.ImageField( _('Avatar'),blank=True,default='../media/useravatar.jpg')

    #created_at = models.DateTimeField(auto_now_add=True,blank=True)
    #updated_at = models.DateTimeField(auto_now=True,blank=True)
   

    def __str__(self):
        return "he"+self.user.username

    def get_absolute_url(self):
        return reverse('core:userprofile-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('core:userprofile-update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('core:userprofile-delete', kwargs={'pk': self.pk})
def create_userprofile(sender, **kwargs):
    if kwargs['created']:
        profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_userprofile, sender=User)
# #############################################################################
# #                                 Category                                 # #
# #############################################################################

 


# #############################################################################
# #                                 Product                                 # #
# #############################################################################

class Product(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_hidden = models.BooleanField(_('Hidden'),default=True)
    category = models.CharField(max_length=25, choices=CATEGORIES, default=CLOTHES)
    shop = models.ForeignKey(UserShop, on_delete=models.CASCADE,verbose_name= _('User'),related_name='products')
    image = models.ImageField( _('Image'),blank=True,default='../media/food.jpg')
 
    title = models.TextField( _('Title'),blank=True, default='')
    description = models.TextField( _('Description'),blank=True, default='')
    price = models.IntegerField( _('Price'),default=100)
    activities = GenericRelation(Activity, related_query_name='products')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('core:product-update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('core:product-delete', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_at']



# #############################################################################
# #                                 Login                                  # #
# #############################################################################

@receiver(user_signed_up)
def set_initial_user_names(request, user, sociallogin=None, **kwargs):
    """
    When a social account is created successfully and this signal is received,
    django-allauth passes in the sociallogin param, giving access to metadata on the remote account, e.g.:

    sociallogin.account.provider  # e.g. 'twitter'
    sociallogin.account.get_avatar_url()

elmarse/core/forms.py
from django import forms
from .models import UserProfile, Product,Message
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

User = get_user_model()
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

class ProductForm(forms.ModelForm):
    #image = forms.ImageField(label=_('Image'),required=False, error_messages = {'invalid':_("Image files only")}, widget=forms.FileInput)
    
   
    class Meta:
        model = Product
        fields = ('image',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)

elmarse/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]
         

        try:
            User.objects.get(email=username,)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

elmarse/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import DetailView, ListView, RedirectView,DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "pk"
    slug_url_kwarg = "pk"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "pk"
    slug_url_kwarg = "pk"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ['first_name', 'last_name', 'email']

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)


user_update_view = UserUpdateView.as_view()

class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('users:list')

user_delete_view = UserDelete.as_view()

class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

elmarse/templates/core/_messages.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %} {% block title %}Home{% endblock %}

{% block content %}
<style media="screen">
.fshrink {
  display: flex;
}
.shop-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
</style>
<div class="container p-10">
  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
    <div class="panel">
        {% load tz %}
        {% if chats.count == 0 %}
            <div class="panel panel-body">{% trans "There is not a single dialogue started" %}</div>
        {% endif %}
        {% for chat in chats %}
            {% if chat.message_set.count != 0 %}
                {% with last_message=chat.message_set.last %}
                    {% get_companion user chat as companion %}
                    <a class="list-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %}" href="{{ chat.get_absolute_url }}">
                        <img class="avatar-messages" src="{{ companion.userprofile.get_avatar }}">
                        <div class="reply-body">
                            <ul class="list-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                </li>
                                <li class="pull-right text-muted"><small>{{ last_message.pub_date }}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <img class="avatar-rounded-sm" src="{{ last_message.author.userprofile.get_avatar }}">
                                    <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
  <div>
    {% if not chat %}
        <div class="card card-body">
            {% trans "It's impossible to start a conversation.No user is found or you do not have access to this conversation." %}
        </div>
    {% else %}
        {% load tz %}
        {% if chat %}
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                            {% include 'core/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="message_form">
            <form id="message-form" class="card card-body" method="post" >
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-default btn-sm" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>{% trans "Отправить" %}</button>
            </form>
        </div>
    {% endif %}
<br><br><br>
  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
<div class="card">
    <div class="card-body">
        <h5 class="card-title">YOU HAVE 5 NEW MESSAGES</h5>
        <div class="message-box">
            <div class="message-widget message-scroll">
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img">
                      <img src="{% static 'avatar.png' %}" alt="user" class="img-circle">
                      <span class="profile-status online pull-right"> </span>
                    </div>
                    <div class="mail-contnet">
                        <h5>Pavan kumar</h5>
                        <span class="mail-desc">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has been.</span> <span class="time">9:30 AM</span> </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img"> <img src="{% static 'avatar.png' %}" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img"> <span class="round">A</span> <span class="profile-status away pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Arijit Sinh</h5> <span class="mail-desc">Simply dummy text of the printing and typesetting industry.</span> <span class="time">9:08 AM</span> </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img"> <img src="{% static 'avatar.png' %}" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img"> <img src="{% static 'avatar.png' %}" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Pavan kumar</h5> <span class="mail-desc">Welcome to the Elite Admin</span> <span class="time">9:30 AM</span> </div>
                </a>
                <!-- Message -->
                <a href="javascript:void(0)">
                    <div class="user-img"> <img src="{% static 'avatar.png' %}" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                </a>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% endblock content %}

elmarse/templates/core/message.html
{% url 'users:profile' message_item.author.username as the_user_url%}
{% load tz %}
<div class="list-group-item {% if not message_item.is_readed %}unreaded{% endif %}">
    <a href="{{ the_user_url }}"><img class="avatar-comment" src="{{ message_item.author.userprofile.get_avatar }}"></a>
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong class="list-group-item-heading"><a href="{{ the_user_url }}">{{ message_item.author.username }}</a></strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message_item.pub_date }}</small></li>
        </ul>
        <div>{{ message_item.message|safe }}</div>
    </div>
</div>

elmarse/templates/core/messages.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% block title %}Messages{% endblock %}

{% block content %}
<style media="screen">
.fshrink {
  display: flex;
}
.shop-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
</style>
<div class="container p-10">
  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
    <div class="panel">
        {% load tz %}
        {% if chats.count == 0 %}
            <div class="panel panel-body">{% trans "There is not a single dialogue started" %}</div>
        {% endif %}
        {% for chat in chats %}
            {% if chat.message_set.count != 0 %}
                {% with last_message=chat.message_set.last %}
                    {% get_companion user chat as companion %}
                    <a class="list-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %}" href="{{ chat.get_absolute_url }}">
                        <img class="avatar-messages" src="{{ companion.userprofile.get_avatar }}">
                        <div class="reply-body">
                            <ul class="list-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                </li>
                                <li class="pull-right text-muted"><small>{{ last_message.pub_date }}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <img class="avatar-rounded-sm" src="{{ last_message.author.userprofile.get_avatar }}">
                                    <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
  <div>
    {% if not chat %}
        <div class="card card-body">
            {% trans "It's impossible to start a conversation.No user is found or you do not have access to this conversation." %}
        </div>
    {% else %}
        {% load tz %}
        {% if chat %}
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                            {% include 'core/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="message_form">w
            <form id="message-form" class="card card-body" method="post" >
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-default btn-sm" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>{% trans "Отправить" %}</button>
            </form>
        </div>
    {% endif %}
<br><br><br>

</div>
</div>
{% endblock content %}

elmarse/templates/core/product_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<div class="container">
  <br>
    <div class="row justify-content-center">
        <div class="col-sm-10 col-md-8 col-lg-6">
          <div class="card">
            <div class="card-body">
            <h3 class="card-title text-center">{% trans "New Product" %}</h3>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form | crispy }}
              <p> <button type="submit" class="btn btn-info btn-block">{% trans "Create" %}</button>
              </p>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
 
  

{% endblock %}

elmarse/templates/core/product_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load socialaccount %}
{% block title %}Poducts{% endblock %}
{% block content %}


<style media="screen">
.fshrink {
  display: flex;
}
.shop-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
</style>


<div class="container p-10">

  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
    {% for product in product_list %}

    <div class="card">
      <div class="fshrink">
          <div class="d-flex m-2 align-items-center ">

            <img class="shop-avatar img img-responsive img-circle" src="{{product.shop.avatar.url}}" />

            <a class="w-100 ml-2 text-info" href="{{product.shop.get_absolute_url}}">{{product.shop.name}}</a>

          </div>
          
      </div>
      <div id="slide{{product.pk}}" class="carousel slide" data-ride="carousel">
    <img class="card-img-top img img-responsive" src="{{product.image.url}}" alt="Card image cap">
          
     </div>
      <div class="card-body">
        <h4 class="card-title">{{product.title}}</h4>
        <p class="card-text">{{product.description}}</p>
      </div>
      <div class="p-2 fshrink border-top">
         
          <div class="w-100 text-center">
            <h4 class="text-info">{{product.price}} MRU </h4>
          </div>
          
      </div>
  
    </div>

     {% endfor %}
  </div>

</div>




<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
 
{% endblock %}

elmarse/templates/core/user_profile.html
<div class="card">
  <div class="fshrink">
      <div class="d-flex m-2 align-items-center">
        <img class="shop-avatar img img-responsive img-circle" src="{{request.user.profile.avatar.url}}" />
        <a class="w-100 ml-2 text-info" href="{{user.get_absolute_url}}">{{request.user}}</a>
      </div>
      <div class="ml-auto m-2">
        <a href="{{request.user.get_update_url}}" class="btn btn-circle btn-outline-secondary"><i class="fa fa-pencil" aria-hidden="false"></i></a>
      </div>
  </div>
   
   
      

 </div>