config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

admin.site.index_title = _('MAURISOUQ')
admin.site.site_header = _('MAURISOUQ Administration')
admin.site.site_title = _('MAURISOUQ Management')

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/",TemplateView.as_view(template_name="pages/about.html"),name="about",),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("user/",include("elmarse.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("core/",include("elmarse.core.urls", namespace="core")), 
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/",default_views.bad_request,kwargs={"exception": Exception("Bad Request!")},),
        path("403/",default_views.permission_denied,kwargs={"exception": Exception("Permission Denied")},),
        path("404/",default_views.page_not_found,kwargs={"exception": Exception("Page not Found")},),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

elmarse/core/urls.py
from django.urls import path

from .views import (
    product_list_view,
    product_create_view,
    product_update_view,
    product_delete_view,
    product_detail_view,
    usershop_detail_view,
    usershop_update_view,
    usershop_list_view,
    usershop_create_view,
    usershop_delete_view,
    approve_view,
    revoke_view
)
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . import views
from .models import Activity,Product

app_name = "core"



urlpatterns = [
     # #############################################################################
    # #                                 Product                                 # #
    # #############################################################################
    path("product/list", view = product_list_view, name="product-list"),
    path('product/create/', product_create_view, name='product-create'),
    path('product/update/<int:pk>/', product_update_view, name='product-update'),
    path('product/<int:pk>/delete/', product_delete_view, name='product-delete'),
    path('product/detail/<int:pk>/', product_detail_view, name='product-detail'),
    # #############################################################################
    # #                                 UserShop                                # #
    # #############################################################################
    path("shop/list", view = usershop_list_view, name="usershop-list"),
    path('shop/create/', usershop_create_view, name='usershop-create'),
    path('shop/detail/<int:pk>/', usershop_detail_view, name='usershop-detail'),
    path('shop/<int:pk>/delete/', usershop_delete_view, name='usershop-delete'),
    path('shop/update/<int:pk>/', usershop_update_view, name='usershop-update'),
    # #############################################################################
    # #                                 Admin                                 # #
    # #############################################################################
    path('approve/<int:user_pk>/', approve_view, name='user-approve'),
    path('revoke/<int:user_pk>/', revoke_view, name='user-revoke'),
]

elmarse/users/urls.py
from django.urls import path

from elmarse.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_delete_view
)

app_name = "users"
urlpatterns = [
    path("list", view=user_list_view, name="list"),
    path("redirect/", view=user_redirect_view, name="redirect"),
    path("update/<str:pk>/", view=user_update_view, name="update"),
    path("delete/<str:pk>/", view=user_delete_view, name="delete"),
    path("detail/<str:pk>/", view=user_detail_view, name="detail"),
]

elmarse/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    is_shopowner = models.BooleanField(default=False)
    email = models.EmailField(_('email address'), blank=False, unique=True)
    first_name = models.CharField(_('first name'), max_length=40, blank=True, null=True, unique=False)
    last_name = models.CharField(_('last name'), max_length=40, blank=True, null=True, unique=False)
    display_name = models.CharField(_('display name'), max_length=14, blank=True, null=True, unique=False)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse('users:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('users:delete', kwargs={'pk': self.pk})

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

elmarse/core/forms.py
from django import forms
from .models import UserProfile, Product,Message
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

User = get_user_model()
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

class ProductForm(forms.ModelForm):
    #image = forms.ImageField(label=_('Image'),required=False, error_messages = {'invalid':_("Image files only")}, widget=forms.FileInput)
    
   
    class Meta:
        model = Product
        fields = ('image',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)

elmarse/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]
         

        try:
            User.objects.get(email=username,)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

elmarse/core/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import TemplateView, DetailView, ListView
from .models import Product , UserProfile,UserShop,Chat,Message
from .forms import ProductForm,MessageForm
from django.http import HttpResponseRedirect
User = get_user_model()
from django.db.models import Count
# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView
import json
from django.http import HttpResponse
from django.views import View
from django.contrib.contenttypes.models import ContentType
from .models import Activity
from django.shortcuts import redirect
 
# #############################################################################
# #                                 UserShop                                # #
# #############################################################################

class UserShopDetail(DetailView):
    queryset = UserShop.objects.filter(user__is_shopowner=True)

usershop_detail_view = UserShopDetail.as_view()

class UserShopUpdate(UpdateView):
    model = UserShop
    fields = ['name','description','image','avatar','phone','address']
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return self.request.user.get_absolute_url()

usershop_update_view = UserShopUpdate.as_view()

class UserShopList(ListView):
    model = UserShop
    template_name_suffix = '_list'
    context_object_name = "usershop_list"

    def get_queryset(self):
        return UserShop.objects.filter(user__is_shopowner=True)

    def get_context_data(self, **kwargs):
        context = super(UserShopList, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        # context['some_data'] = 'This is just some data'
        return context

usershop_list_view = UserShopList.as_view()

 
class UserShopCreate(CreateView):
    model = UserShop
    fields = ['name','description','image','avatar','phone','address']

    template_name_suffix = '_create_form'
    success_url = reverse_lazy('core:usershop-list')

usershop_create_view = UserShopCreate.as_view()

class UserShopDelete(DeleteView):
    model = UserShop
    success_url = reverse_lazy('core:usershop-list')

usershop_delete_view = UserShopDelete.as_view()

# #############################################################################
# #                                 Products                                # #
# #############################################################################

class ProductDetail(DetailView):
    queryset = Product.objects.annotate(count=Count('activities'))
    def get_context_data(self, **kwargs):

        context = super(ProductDetail, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        user = self.request.user
        activity = Activity.objects.all().\
        filter(content_type__model='product',user=user, activity_type=1).first()
        context['activity'] = activity
        return context

product_detail_view = ProductDetail.as_view()
from django.db.models import Count
from django.db.models import Q
class ProductList(ListView):
    model = Product
    template_name = 'core/product_list.html'
    context_object_name = "product_list"

    def get_products(self):
        user =self.request.user
        products = Product.objects.filter(is_hidden=False,shop__user__is_shopowner=True)
         
        return products

    def get_queryset(self):
        return  self.get_products()
        # {'tags__count': 3}

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)


        return context

product_list_view = ProductList.as_view()
 
class ProductCreate(CreateView):
    model = Product
    fields = ['title','description','image','price','category','is_hidden']

    template_name_suffix = '_create_form'
    success_url = reverse_lazy('core:product-list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        # things
        self.object.shop = self.request.user.shop
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
        
   
product_create_view = ProductCreate.as_view()


class ProductUpdate(UpdateView):
    model = Product
    fields =  ['title','description','image','price','category','is_hidden']
    template_name_suffix = '_update_form'
     
    def get_success_url(self):
        return self.request.user.get_absolute_url()


product_update_view = ProductUpdate.as_view()

class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('core:product-list')

product_delete_view = ProductDelete.as_view()

# #############################################################################
# #                                 Products                                # #
# #############################################################################

def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('settings:profile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def approve(request,user_pk):
    if request.method == 'GET' and request.user.is_superuser:
        user = User.objects.filter(pk=user_pk).first()
        if user:
            user.is_shopowner =True
            user.save()
    
    return redirect('users:list')

approve_view = approve

def revoke(request,user_pk):
    if request.method == 'GET' and request.user.is_superuser:
        user = User.objects.filter(pk=user_pk).first()
        if user:
            user.is_shopowner =False
            user.save()
    
    return redirect('users:list')

revoke_view = revoke

elmarse/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import DetailView, ListView, RedirectView,DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "pk"
    slug_url_kwarg = "pk"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "pk"
    slug_url_kwarg = "pk"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ['first_name', 'last_name', 'email']

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)


user_update_view = UserUpdateView.as_view()

class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('users:list')

user_delete_view = UserDelete.as_view()

class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

elmarse/templates/users/user_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ object }}{% endblock %}

{% block content %}

  <h1>{{ object }}</h1>

  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "<h1>{{ object.name }}</h1>"?</p>
      <input type="submit" value="Confirm">
  </form>
{% endblock %}

elmarse/templates/users/user_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load socialaccount %} {% block title %}Home{% endblock %}

{% block content %}
<style media="screen">
.fshrink {
  display: flex;
}
.shop-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
</style>
<div class="container p-10">

  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
      {% if object == request.user %}
      {% include "core/user_profile.html" %}
      {% include "core/shopowner_profile.html" %}
      {% else %}
      <p>You don't have aceess to this page</p>
      {% endif %}
    

  </div>
    <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">


   


  


</div>
</div>
{% endblock content %}

elmarse/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% load socialaccount %} {% block title %}{% trans "Update" %}{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-10 col-md-8 col-lg-6">
          <div class="card">
            <div class="card-body">
            <h3 class="card-title text-center">{% trans "Update" %} </h3>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form | crispy }}
              <p> <button type="submit" class="btn btn-info btn-block">{% trans "Update" %}</button>
              </p>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
 
{% endblock %}

elmarse/templates/users/user_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load socialaccount %}
{% block title %}Members{% endblock %}
{% block content %}


<style media="screen">
.fshrink {
  display: flex;
}
.shop-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
}
</style>


<div class="container p-10">

  {% if request.user.is_superuser %}
  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
      <div class="card text-center card-title">
         <div class="pt-2 text-center">  
             <h3><span class="badge badge-pill badge-success">{% trans "Approved users" %}</span></h3>
       </div>
      </div>
    
     {% for user in user_list %}
      
     {% if user.is_shopowner %}
     <div class="card">
         <div class="fshrink">
             <div class="d-flex m-2 align-items-center ">
               <img class="shop-avatar img img-responsive img-circle" src="{{user.profile.avatar.url}}" />
   
               <a class="w-100 ml-2 text-info">{{user.username}}</a>
             </div>
             <div class="m-2 ml-auto">
                 {% if user.is_shopowner %}
                 <a class="btn btn-danger btn-rounded" href="{% url 'core:user-revoke' user.pk %}">{% trans "Revoke" %}</a>
                 {% else %}
                 <a class="btn btn-success btn-rounded" href="{% url 'core:user-approve' user.pk %}">{% trans "Approve" %}</a>
                 {% endif %}
             </div>
         </div>
         
       </div>
     {% else %}
     {% endif %}
 
      {% endfor %}
   </div>
   <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
    
       <div class="card text-center card-title">
          
          <div class="pt-2 text-center">  
              <h3><span class="badge badge-pill badge-info">{% trans "Pending users" %}</span></h3>
        </div>
       </div>
     {% for user in user_list %}
      
    {% if not user.is_shopowner %}
    <div class="card">
        <div class="fshrink">
            <div class="d-flex m-2 align-items-center ">
              <img class="shop-avatar img img-responsive img-circle" src="{{user.profile.avatar.url}}" />
   
              <a class="w-100 ml-2 text-info">{{user.username}}</a>
            </div>
            <div class="m-2 ml-auto">
                 
                <a class="btn btn-success btn-rounded" href="{% url 'core:user-approve' user.pk %}">{% trans "Approve" %}</a>
                 
            </div>
        </div>
        
      </div>
    {% else %}
    {% endif %}
  
      {% endfor %}
   </div>
  {% else %} 
  <div class="col-md-10 col-lg-8 offset-lg-2 offset-md-1">
      <div class="card text-center card-title">
          <div class="pt-2 text-center">  
            <p> {% trans "You don't have access to this page!" %} </p>
        </div>
      </div>
      </div>
      
  {% endif %}
  
</div>

 
{% endblock content %}